# Generated by Django 3.2 on 2021-04-22 16:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Intitulé de la Filière')),
            ],
            options={
                'verbose_name': 'Filière',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name="Intitulé de l'Université")),
            ],
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=220, null=True, verbose_name='Thème du mémoire')),
                ('supervisor', models.CharField(blank=True, max_length=120, null=True, verbose_name='Encadreur')),
                ('middleClass', models.FloatField(blank=True, default=0, null=True, verbose_name='Note obtenue')),
                ('mention', models.CharField(blank=True, choices=[('Passable', 'Passable'), ('Assez-bien', 'Assez-bien'), ('Bien', 'Bien'), ('Très-bien', 'Très-bien'), ('Excellente', 'Excellente')], max_length=20, null=True, verbose_name='Mention')),
                ('stateBefore', models.BooleanField(default=False, verbose_name='Statut avant la Soutenance')),
                ('stateAfter', models.BooleanField(default=False, verbose_name='Satut après la soutenance')),
                ('depositDay', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('abstract', models.TextField(blank=True, null=True)),
                ('presentationImage', models.ImageField(blank=True, null=True, upload_to='image_memoire/', verbose_name='Image de présentation')),
                ('document', models.FileField(upload_to='document_memoire/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Veuillez charger uniquement des documents de type pdf.')], verbose_name='Document du Mémoire')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_memoire/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'], message='Veuillez charger uniquement des documents de type mp4.')], verbose_name='Vidéo du Mémoire')),
                ('entity', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.entity', verbose_name='Filière')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty', verbose_name='Ecole/Faculté/Institut')),
            ],
            options={
                'verbose_name': 'Mémoire',
                'ordering': ['-depositDay'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name="Intitulé de l'Université")),
            ],
            options={
                'verbose_name': 'Université',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Prénom')),
                ('inscription_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Inscription")),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Prénom')),
                ('inscription_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Inscription")),
                ('memoire', models.ManyToManyField(blank=True, to='accounts.Memoire')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Option')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.entity', verbose_name='Filière')),
            ],
            options={
                'ordering': ['entity__name'],
            },
        ),
        migrations.AddField(
            model_name='memoire',
            name='option',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.option'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.university', verbose_name='Université'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university'),
        ),
        migrations.AddField(
            model_name='entity',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
    ]
