# Generated by Django 3.2 on 2015-09-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='academicYear',
            field=models.CharField(default='2014-2015', max_length=20, verbose_name='Année Académique'),
        ),
    ]
