# Generated by Django 3.2 on 2021-04-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_memoire_academicyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Ecole/Institut/Faculté'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='memoire',
        ),
        migrations.AddField(
            model_name='student',
            name='lmemoire',
            field=models.ManyToManyField(blank=True, to='accounts.Memoire', verbose_name='Mémoires'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty', verbose_name='Ecole/Institut/Faculté'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=110, verbose_name="Intitulé de le l'école/Institut/Faculté"),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='Université'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='academicYear',
            field=models.CharField(choices=[('2020-2021', '2020-2021')], default='2020-2021', max_length=20, verbose_name='Année Académique'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='accounts.Teacher', verbose_name='Enseignants assignés'),
        ),
    ]
