# Generated by Django 3.2 on 2021-04-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210424_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lmemoire',
            new_name='memoire',
        ),
    ]
