# Generated by Django 3.2 on 2021-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210426_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatar/'),
        ),
    ]
